plt.figure(figsize=(6,4))
sns.countplot(data=df, x='FLAG_OWN_REALTY', hue='aligibility')
plt.title("Property Ownership vs Eligibility")
plt.xlabel("Owns Property (0=No, 1=Yes)")
plt.ylabel("Count")
plt.show()